# Generated by Django 4.0.4 on 2022-05-10 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='date',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='number',
            new_name='expiration_date',
        ),
    ]
