# Generated by Django 4.0.4 on 2022-05-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_date_card_card_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luhn_algorithm_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=100)),
                ('expiration_date', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
            ],
        ),
    ]
