# Generated by Django 4.0.4 on 2022-05-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_card_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='luhn_algorithm_card',
            name='card_number',
            field=models.CharField(max_length=100),
        ),
    ]
